alter table public.foods
  add column if not exists generic_name text,
  add column if not exists quantity text,
  add column if not exists categories text,
  add column if not exists categories_tags text[],
  add column if not exists countries text,
  add column if not exists countries_tags text[],
  add column if not exists ingredients_text text,
  add column if not exists ingredients_tags text[],
  add column if not exists allergens text,
  add column if not exists allergens_tags text[],
  add column if not exists additives_tags text[],
  add column if not exists nutriscore_score int,
  add column if not exists nutriscore_grade text,
  add column if not exists nova_group int,
  add column if not exists nutrient_levels_tags text[],
  add column if not exists image_small_url text,
  add column if not exists image_ingredients_url text,
  add column if not exists image_nutrition_url text,
  add column if not exists completeness numeric(5,4);

alter table public.food_servings
  add column if not exists energy_kj numeric(12,4),
  add column if not exists saturated_fat_gr numeric(12,4),
  add column if not exists trans_fat_gr numeric(12,4),
  add column if not exists cholesterol_gr numeric(12,6),
  add column if not exists sugars_gr numeric(12,4),
  add column if not exists added_sugars_gr numeric(12,4),
  add column if not exists fiber_gr numeric(12,4),
  add column if not exists salt_gr numeric(12,4),
  add column if not exists sodium_gr numeric(12,6),
  add column if not exists alcohol_gr numeric(12,4),
  add column if not exists vitamin_a_gr numeric(12,8),
  add column if not exists vitamin_c_gr numeric(12,8),
  add column if not exists vitamin_d_gr numeric(12,8),
  add column if not exists vitamin_e_gr numeric(12,8),
  add column if not exists vitamin_b1_gr numeric(12,8),
  add column if not exists vitamin_b2_gr numeric(12,8),
  add column if not exists vitamin_b6_gr numeric(12,8),
  add column if not exists vitamin_b9_gr numeric(12,8),
  add column if not exists vitamin_b12_gr numeric(12,10),
  add column if not exists calcium_gr numeric(12,8),
  add column if not exists iron_gr numeric(12,8),
  add column if not exists magnesium_gr numeric(12,8),
  add column if not exists zinc_gr numeric(12,8),
  add column if not exists potassium_gr numeric(12,8),
  add column if not exists phosphorus_gr numeric(12,8),
  add column if not exists caffeine_gr numeric(12,8),
  add column if not exists nutrients_100g jsonb;

create index if not exists foods_source_name_idx on public.foods (source, name);
